geyser: false #ставьте true если у вас установлен гейзер
max-experience-pre-generated-location: 50 #Максимальное количество попыток подобрать заранее сгенерированную локацию
License: ''
debug: false
log-level: LOW
settings:
  world-guard-flags: #Флаги WorldGuard
    allow-flags: #разрешённые
      - use
      - pvp
      - chest-access
    deny-flags: #запрещённые
      - creeper-explosion
      - tnt
      - fire-spread
      - lava-fire
      - other-explosion

#При включении обратный отсчёт у всех аирдропов будет выключен
#Раз в time минут плагин будет включать обратный отсчёт до старта у случайного аирдропа
#При этом в summoner при clone: false никак не будет влиять на этот таймер
#Все аирдропы призванные глобальным таймером являются клонами
global-time:
  enable: false
  time: 90

summoner-сooldown: 1200 #В тиках
summoner:
  item-1:
    material: SOUL_CAMPFIRE
    nbt:
    name: '&aМаяк призыва аирдропа'
    lore:
      - '&7line 1'
      - '&7line 2'
    airdrop: RANDOM
    clone: true #клонировать ли аирдроп, если true то все призывные аирдропы будут клонами
    use-player-location: true #спавнить аирдроп на место призыва
    check-up-blocks: false # проверять блоки над аирдропом
    flatness-check: false #проверка ровности
    ignore-region: false
    call: [ ] # сюда можно добавить имена слушателей, которые вызовутся, добавлять также как в lore
  item-2:
    material: SOUL_CAMPFIRE
    nbt:
    name: '&aМаяк призыва аирдропа'
    lore:
      - '&7line 1'
      - '&7line 2'
    airdrop: RANDOM
    clone: true
    flatness-check: false
    use-player-location: false
    check-up-blocks: false
    ignore-region: false
    call: [ ]


custom-crafts:
  enable: false
  crafts:
    craft-1:
      summoner: item-1
      ingredients:
        A: DIAMOND
        B: BEDROCK
      slots:
        top: 'AAA'
        middle: 'ABA'
        bottom: 'AAA'


compass:
  material: COMPASS
  nbt:
  item-name: '&aКомпас'
  item-lore:
    - '&7Указывает путь до ближайшего аирдропа'
  line-max-distance: 10
  particle-step: 0.2
  particle-color: '255:0:0' #r:g:b
  particle-size: 3
  message-not-found: '&cСейчас нет активных аирдропов! &7ближайший через %bairdrop_time_start_format%'
  message-found: null



auto-enchant:
  enable: false
  en1:
    material: NETHERITE_PICKAXE
    efficiency:
      chance: 70
      min-level: 2
      max-level: 5
    fortune:
      chance: 30
      min-level: 1
      max-level: 2
    conflict-enchant:
      - silk_touch
  en2:
    material: NETHERITE_PICKAXE
    silk_touch:
      chance: 70
      min-level: 1
      max-level: 1
    conflict-enchant:
      - fortune
      - efficiency

